enum TextureKey {
  BtnIcon = 'btnIcon',
  BtnText = 'btnText',
  BtnCursor = 'btnCursor',
  Particle = 'particle',
  ParticleTransformer = 'particleTransformer',
  ParticleJump = 'particleJump',
  ParticleCoin = 'particleCoin',
  Fireball = 'fireball',
  Spike = 'spike',
  Enemy2 = 'enemy2',
  SpikyBall = 'spikyBall',
  Cloud = 'cloud',
  Hill = 'hill',
  Hill2 = 'hill2',
  Grid = 'grid',
  Icons = 'icons',
  FontHeading = 'Luckiest Guy',
  FontBody = 'Lato',
}

export default TextureKey

export enum IconsKey {
  Settings,
  Back,
  Pause,
  Play,
  Restart,
  Levels,
  Edit,
  Move,
  Close,
  Rect,
  Eraser,
  Platform,
  Bobby,
  Target,
  Export,
  Import,
  Spike,
  Test,
  FallingBlock,
}
