enum TextureKey {
  BtnIcon = 'btnIcon',
  BtnText = 'btnText',
  BtnCursor = 'btnCursor',
  Particle = 'particle',
  ParticleTransformer = 'particleTransformer',
  ParticleLava = 'particleLava',
  ParticleJump = 'particleJump',
  ParticleCoin = 'particleCoin',
  Fireball = 'fireball',
  Spike = 'spike',
  Enemy2 = 'enemy2',
  SpikyBall = 'spikyBall',
  Cloud = 'cloud',
  Hill = 'hill',
  Hill2 = 'hill2',
  Volcanos = 'volcanos',
  Volcanos2 = 'volcanos2',
  Grid = 'grid',
  Grid2 = 'grid2',
  Bump = 'bump',
  Icons = 'icons',
  FontHeading = 'Luckiest Guy',
  FontBody = 'Lato',
}

export default TextureKey

export enum IconsKey {
  Settings,
  Back,
  Pause,
  Play,
  Restart,
  Levels,
  Edit,
  Move,
  Close,
  Rect,
  Eraser,
  Platform,
  Bobby,
  Target,
  Export,
  Import,
  Spike,
  Test,
  FallingBlock,
  SpikyBall,
  Select,
  Active,
  Delete,
  Cannon,
  Plus,
  Minus,
  OneWayPlatform,
  Enemy,
  Chevron,
  Bump,
  Coin,
}
